# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
spring:
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.244.193:3306/examples
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    top.zuoyu.mybatis.temp.mapper: debug

